name: Feature ticket
description: Request a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What do you need, and why?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggested solution
    validations:
      required: false
